name: Joongang News Crawler

on:
  schedule:
    # 매일 한국 시간 기준 오전 6시 (UTC 시간 기준으로 -9시간 계산)
    - cron: '0 21 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 사용하시는 Python 버전으로 설정하세요.
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tqdm

    - name: Run crawler
      run: python "JoongAng_crawler.py"  # 스크립트 경로를 정확히 지정하세요.

    - name: Commit and push
      run: |
        git config --global user.email "abs3011@konkuk.ac.kr"
        git config --global user.name "Kyuwon"
        git add result/joongang_newsTest.csv
        git commit -m "Update Joongang News Data csv $(date +'%Y-%m-%d')"
        git push
